In [108]:
#preprocessing packages
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

#models 
from sklearn.linear_model import LogisticRegression  #LOGISTIC
from sklearn.svm import SVC                          #SVM
from sklearn.naive_bayes import GaussianNB           #NAIVEBAYES
from sklearn.neighbors import KNeighborsClassifier   #KNN
from sklearn.ensemble import RandomForestClassifier  #RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier      #DecisionTreeClassifier

#performance_evaluation
from sklearn.metrics import accuracy_score


In [109]:
data=pd.read_csv(r'D:\Datasets\heart.csv')
data

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [149]:
data.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [110]:
data1 = data.drop(['Age','Sex'],axis=1)
data1

ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0             ATA        140          289          0     Normal    172   
1             NAP        160          180          0     Normal    156   
2             ATA        130          283          0         ST     98   
3             ASY        138          214          0     Normal    108   
4             NAP        150          195          0     Normal    122   
..            ...        ...          ...        ...        ...    ...   
913            TA        110          264          0     Normal    132   
914           ASY        144          193          1     Normal    141   
915           ASY        130          131          0     Normal    115   
916           ATA        130          236          0        LVH    174   
917           NAP        138          175          0     Normal    173   

    ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0                N      0.0       Up             0  
1                N      1.0     Flat             1  
2                N      0.0       Up             0  
3                Y      1.5     Flat             1  
4                N      0.0       Up             0  
..             ...      ...      ...           ...  
913              N      1.2     Flat             1  
914              N      3.4     Flat             1  
915              Y      1.2     Flat             1  
916              N      0.0     Flat             1  
917              N      0.0       Up             0  

[918 rows x 10 columns]

In [111]:
le = LabelEncoder()
data1['ChestPainType']=le.fit_transform(data1['ChestPainType'])
data1['ChestPainType']

data1['RestingECG']=le.fit_transform(data1['RestingECG'])
data1['RestingECG']

data1['ExerciseAngina']=le.fit_transform(data1['ExerciseAngina'])
data1['ExerciseAngina']

data1['ST_Slope']=le.fit_transform(data1['ST_Slope'])
data1['ST_Slope']

0      2
1      1
2      2
3      1
4      2
      ..
913    1
914    1
915    1
916    1
917    2
Name: ST_Slope, Length: 918, dtype: int32

In [112]:
data1

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0                1        140          289          0           1    172   
1                2        160          180          0           1    156   
2                1        130          283          0           2     98   
3                0        138          214          0           1    108   
4                2        150          195          0           1    122   
..             ...        ...          ...        ...         ...    ...   
913              3        110          264          0           1    132   
914              0        144          193          1           1    141   
915              0        130          131          0           1    115   
916              1        130          236          0           0    174   
917              2        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0                 0      0.0         2             0  
1                 0      1.0         1             1  
2                 0      0.0         2             0  
3                 1      1.5         1             1  
4                 0      0.0         2             0  
..              ...      ...       ...           ...  
913               0      1.2         1             1  
914               0      3.4         1             1  
915               1      1.2         1             1  
916               0      0.0         1             1  
917               0      0.0         2             0  

[918 rows x 10 columns]

In [113]:
X = data1.iloc[:,:-1]
X

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0                1        140          289          0           1    172   
1                2        160          180          0           1    156   
2                1        130          283          0           2     98   
3                0        138          214          0           1    108   
4                2        150          195          0           1    122   
..             ...        ...          ...        ...         ...    ...   
913              3        110          264          0           1    132   
914              0        144          193          1           1    141   
915              0        130          131          0           1    115   
916              1        130          236          0           0    174   
917              2        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  
0                 0      0.0         2  
1                 0      1.0         1  
2                 0      0.0         2  
3                 1      1.5         1  
4                 0      0.0         2  
..              ...      ...       ...  
913               0      1.2         1  
914               0      3.4         1  
915               1      1.2         1  
916               0      0.0         1  
917               0      0.0         2  

[918 rows x 9 columns]

In [114]:
Y = data1['HeartDisease']
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [115]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model = LogisticRegression()
model


LogisticRegression()

In [116]:
model.fit(X_train,Y_train)

y_pred = model.predict(X_test)
y_pred


C:\Users\suresh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [117]:
ac = accuracy_score(y_pred,Y_test)
ac

0.8206521739130435

In [118]:
#SVM

model=SVC()
model

SVC()

In [119]:
model.fit(X_train,Y_train)


SVC()

In [120]:
Y_pred = model.predict(X_test)
Y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [121]:
ac = accuracy_score(Y_test,Y_pred)
ac

0.6793478260869565

In [122]:
#NaiveBayes

model = GaussianNB()
model

GaussianNB()

In [123]:
model.fit(X_train,Y_train)

GaussianNB()

In [124]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [125]:
ac = accuracy_score(Y_test,y_pred)
ac

0.8478260869565217

In [126]:
#KNN

model = KNeighborsClassifier()
model

KNeighborsClassifier()

In [127]:
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [128]:
ac = accuracy_score(Y_test,y_pred)
ac

0.6684782608695652

In [191]:
#RandomClassifier

model = RandomForestClassifier(random_state=42)
model

RandomForestClassifier(random_state=42)

In [192]:
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [195]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [196]:
ac = accuracy_score(y_pred,Y_test)
ac

0.9021739130434783

In [168]:
#DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)
model

DecisionTreeClassifier(random_state=42)

In [169]:
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [170]:
ac = accuracy_score(y_pred,Y_test)
ac

0.8097826086956522